apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: valkey
  namespace: ember-ai
spec:
  serviceName: "valkey-svc"
  replicas: 1
  selector:
    matchLabels:
      app: valkey
  template:
    metadata:
      labels:
        app: valkey
    spec:
      containers:
      - name: valkey
        image: valkey/valkey:7.2.5
        ports:
        - containerPort: 6379
        command: ["valkey-server"]
        args: ["--appendonly", "yes"]
        volumeMounts:
        - name: valkey-data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: valkey-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi

---
apiVersion: v1
kind: Service
metadata:
  name: valkey-svc
  namespace: ember-ai
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: valkey
  clusterIP: None
